// ============================================================
//  BuildMate News Data  –  news-data.js
//  このファイルを編集するだけで news.html と index.html の
//  両方に自動反映されます。
// ============================================================

const categoryImages = {
            "AI活用": "images/aikatsuyou_sum.png", 
            "アフター": "images/after_sum.png",
            "事例": "images/jirei_sum.png", 
            "業務効率化": "images/gyoumu_sum.png", 
            "DX": "images/dx_sum.png", 
            "採用": "images/saiyou_sum.png", 
            "営業": "images/eigyou_sum.png",
            "GAS活用": "images/gas_sum.png"
        };

const allArticles = [
            { title: "工務店の竣工書類・完成写真の整理をAI・GASで自動化する方法｜2時間→20分に短縮", tag: "GAS活用", image: "images/genba_sum.png", date: "2026.04.17", content: `<p>竣工時の書類整理と写真の仕分けに2時間以上かかっていませんか？</p>` },
            { title: "工務店のスケジュール・シフト管理をGASで自動化する方法｜30分→5分に短縮", tag: "GAS活用", image: "images/gas_sum.png", date: "2026.04.16", content: `<p>誰がどの現場に入るか、毎朝調整に追われていませんか？</p>` },
            { title: "工務店の採用・外注業務をAI・GASで効率化する方法【完全まとめ】", tag: "GAS活用", image: "images/gyoumu_sum.png", date: "2026.04.15", content: `<p>人手不足の解消と外注コスト管理、どちらも後回しになっていませんか？</p>` },
            { title: "工務店の産業廃棄物マニフェスト管理をGASで自動化する方法｜月3時間→自動化", tag: "GAS活用", image: "images/gas_sum.png", date: "2026.04.14", content: `<p>マニフェストの管理が追いつかず、提出期限を見落としたことはありませんか？</p>` },
            { title: "工務店の引渡し後満足度アンケート送付をGASで自動化する方法｜毎回30分→自動化", tag: "GAS活用", image: "images/gas_sum.png", date: "2026.04.13", content: `<p>引渡し後のアンケート送付を、毎回忘れずに対応できていますか？</p>` },
            { title: "工務店の来場アンケート集計・分析をAI・GASで自動化する方法｜3時間→20分に短縮", tag: "GAS活用", image: "images/gas_sum.png", date: "2026.04.12", content: `<p>見学会後にアンケートを集めたまま、活用できていないという状況はありませんか？</p>` },
            { title: "ニュースレター作成時間を3日から30分に短縮する技", tag: "アフター", image: "images/after_sum.png", date: "2026.04.09", content: `<p>季節のネタや地域情報をAIに提案させ、構成案を作らせます。あとは現場の写真を数枚はめ込むだけで、温かみのある紙面が完成します。</p>` },
            { title: "工務店の勤怠管理をAI・GASで自動化する方法｜月4時間→30分に短縮", tag: "GAS活用", image: "images/gas_sum.png", date: "2026.04.08", content: `<p>月末の勤怠集計に半日かかって、給与計算が毎月ギリギリになっていませんか？</p>` },
            { title: "工務店の定期点検スケジュール管理をGASで自動化する方法｜月2時間→自動化", tag: "GAS活用", image: "images/genba_sum.png", date: "2026.04.07", content: `<p>引渡しが増えるにつれて点検の管理が追いつかなくなっていませんか？</p>` },
            { title: "工務店の品質チェック・社内検査をAIで効率化する方法｜1時間→30分に短縮", tag: "GAS活用", image: "images/gyoumu_sum.png", date: "2026.04.06", content: `<p>社内検査でチェック項目を見落として、引渡し後にやり直しになったことはありませんか？</p>` },
            { title: "工務店のGAS（Google Apps Script）活用完全ガイド【2026年版】", tag: "GAS活用", image: "images/gas_sum.png", date: "2026.04.05", content: `<p>GASはGoogleの無料ツールです。工務店の業務を追加費用ゼロで自動化できます。</p>` },
            { title: "工務店の応募者の選考・面接調整をGASで自動化する方法｜毎回1時間→15分に短縮", tag: "GAS活用", image: "images/gas_sum.png", date: "2026.04.04", content: `<p>応募が来るたびにメール対応と面接調整に1時間以上かかっていませんか？</p>` },
            { title: "「売りっぱなし」と言わせない。AIで書く心のこもった手紙術", tag: "アフター", image: "images/after_sum.png", date: "2026.04.03", content: `<p class="font-bold text-xl mb-6 text-wa-brand">デジタルの力で、アナログな温もりを。</p><p>引き渡し後の定期点検、ハガキ一通で済ませていませんか？AIを使えば、お客様一人ひとりの家族構成や趣味に合わせた、温かみのある手紙を数分で作成できます。</p><div class="bg-wa-bg p-6 rounded-lg border border-wa-brand/20 my-6 italic text-wa-gray">「先日のお子様の入学式はいかがでしたか？」</div><p>こうした一言を添えるだけで、お客様との関係性は劇的に変わります。</p>` },
            { title: "工務店の未対応タスクリマインドをGASで自動化してChatwork・LINEに通知する方法", tag: "GAS活用", image: "images/gas_sum.png", date: "2026.04.02", content: `<p>「あの件、対応していたっけ？」と後から気づくことはありませんか？</p>` },
            { title: "現場の清掃状況を画像解析でスコアリングしてみた", tag: "DX", image: "images/dx_sum.png", date: "2026.04.01", content: `<p>現場写真をAIが解析し、「整理整頓度」を点数化。ゲーム感覚で職人のモチベーションを上げましょう。</p>` },
            { title: "工務店のアフター対応業務をAI・GASで効率化する方法【完全まとめ】", tag: "GAS活用", image: "images/gyoumu_sum.png", date: "2026.03.31", content: `<p>アフター対応の漏れがお客様の信頼と再受注機会を同時に失わせていませんか？</p>` },
            { title: "工務店の設計・積算をAI・GASで効率化する方法｜間取り作成から見積書まで自動化", tag: "GAS活用", image: "images/keiri_sum.png", date: "2026.03.30", content: `<p>工務店の設計・積算業務をAI・GASで効率化する方法を解説します。</p>` },
            { title: "工務店の社内マニュアル・手順書の整備をAIで効率化する方法｜半日→1時間に短縮", tag: "GAS活用", image: "images/gyoumu_sum.png", date: "2026.03.29", content: `<p>新人が入るたびに口頭で説明を繰り返していませんか？</p>` },
            { title: "工務店の現場管理をAI・GASで効率化する方法｜工程表・施工写真・品質管理を自動化", tag: "GAS活用", image: "images/genba_sum.png", date: "2026.03.28", content: `<p>工務店の現場管理業務をAI・GASで効率化する方法を解説します。</p>` },
            { title: "工務店の週次経営サマリーをGASで自動生成してChatworkに配信する方法", tag: "GAS活用", image: "images/gas_sum.png", date: "2026.03.27", content: `<p>先週の受注件数・問い合わせ数、すぐに答えられますか？</p>` },
            { title: "工務店のOB客向けDM・ニュースレターをAI・GASで自動化する方法｜月4時間→30分を実現", tag: "GAS活用", image: "images/gas_sum.png", date: "2026.03.26", content: `<p>OB客へのDM、毎月きちんと送れていますか？</p>` },
            { title: "OB訪問の予定調整をAIカレンダーで自動化する", tag: "アフター", image: "images/after_sum.png", date: "2026.03.25", content: `<p>空き時間を提示し、お客様に選んでもらうだけの予約システムを導入すれば、日程調整のコストはゼロになります。</p>` },
            { title: "会議時間を半分に。ファシリテーターとしてのAI活用", tag: "業務効率化", image: "images/gyoumu_sum.png", date: "2026.03.23", content: `<p>AIに会議音声を聞かせ、議論の整理と議事録作成を任せることで、生産性の高い会議運営が可能になります。</p>` },
            { title: "工務店のSNS投稿ネタをGemini APIとGASで毎朝自動提案する方法", tag: "GAS活用", image: "images/gyoumu_sum.png", date: "2026.03.22", content: `<p>「今日は何を投稿しよう？」と毎朝悩んでいませんか？</p>` },
            { title: "2026年問題に備える。建設DXの最初の一歩とは", tag: "DX", image: "images/dx_sum.png", date: "2026.03.20", content: `<p>職人の高齢化と人手不足が加速する2026年問題。ベテランの技を動画に残し、AIでマニュアル化することで、若手の育成スピードを上げましょう。</p>` },
            { title: "建設現場の施工写真をLINE×GASでGoogleドライブに自動整理する方法", tag: "GAS活用", image: "images/genba_sum.png", date: "2026.03.19", content: `<p>現場の写真、LINEで送ってそのまま放置になっていませんか？</p>` },
            { title: "工務店のAI・GAS導入完全ガイド｜業務効率化76本まとめ【2026年版】", tag: "GAS活用", image: "images/gyoumu_sum.png", date: "2026.03.18", content: `<p>「どこから手をつければいいかわからない」という工務店のためのガイドです。</p>` },
            { title: "工務店の業者・外注への支払処理をGASで自動集計する方法｜支払いミスをゼロに", tag: "GAS活用", image: "images/keiri_sum.png", date: "2026.03.17", content: `<p>月末の支払い処理、何時間かかっていますか？</p>` },
            { title: "工務店の備品・消耗品の発注・在庫管理をGASで自動化する方法｜週1時間→自動化", tag: "GAS活用", image: "images/gas_sum.png", date: "2026.03.15", content: `<p>現場で急に備品が切れて作業が止まった、という経験はありませんか？</p>` },
            { title: "工務店の住宅ローン・補助金案内をAIで効率化する方法｜1時間→15分に短縮", tag: "GAS活用", image: "images/keiri_sum.png", date: "2026.03.14", content: `<p>補助金の種類が多すぎて、お客様に正確に案内できているか不安ではありませんか？</p>` },
            { title: "工務店の競合調査・市場リサーチをAIで自動化する方法｜半日→1時間に短縮", tag: "GAS活用", image: "images/gyoumu_sum.png", date: "2026.03.13", content: `<p>近隣の競合工務店が何をやっているか、なかなか把握できていませんか？</p>` },
            { title: "紙の日報はもう古い？音声入力で終わらせる現場報告", tag: "業務効率化", image: "images/gyoumu_sum.png", date: "2026.03.12", content: `<p>現場から疲れて帰ってきた後に書く日報は苦痛です。LINEに向かって喋るだけで、AIが日報フォーマットに変換し自動保存する仕組みを作りましょう。</p>` },
            { title: "工務店のチラシ・DM作成をAIで効率化する方法｜半日の作業を2時間に短縮", tag: "GAS活用", image: "images/gyoumu_sum.png", date: "2026.03.11", content: `<p>チラシの文言を考えるだけで半日が終わってしまう、そんな経験はありませんか？</p>` },
            { title: "在庫管理の適正化！現場の余り材を無駄にしない方法", tag: "業務効率化", image: "images/gyoumu_sum.png", date: "2026.03.10", content: `<p>倉庫の余り材を写真で共有し、「使える在庫リスト」を可視化することで、無駄な発注を防ぎます。</p>` },
            { title: "工務店の設計・積算業務をAI・GASで効率化する方法【完全まとめ】", tag: "GAS活用", image: "images/keiri_sum.png", date: "2026.03.09", content: `<p>設計・積算業務の非効率が受注スピードと利益を同時に削っていませんか？</p>` },
            { title: "工務店のクレーム・不具合受付をAI・GASで自動化する方法｜30分→5分で対応速度を改善", tag: "GAS活用", image: "images/gas_sum.png", date: "2026.03.08", content: `<p>クレームへの初動が遅れると、小さな不満が大きな問題になります。</p>` },
            { title: "工務店の社内管理をAI・GASで効率化する方法｜日報・勤怠・会議録を自動化", tag: "GAS活用", image: "images/gyoumu_sum.png", date: "2026.03.07", content: `<p>工務店の社内管理業務をAI・GASで効率化する方法を解説します。</p>` },
            { title: "工務店の確認申請書類の準備・提出管理をAI・GASで自動化する方法｜半日→2時間に短縮", tag: "GAS活用", image: "images/gas_sum.png", date: "2026.03.06", content: `<p>確認申請の書類不備で審査が差し戻しになった経験はありませんか？</p>` },
            { title: "協力業者とのFAXやり取りを卒業するステップ", tag: "DX", image: "images/dx_sum.png", date: "2026.03.05", content: `<p>スマホ発注を導入することで、「言った言わない」がなくなり、履歴が残るメリットを協力業者にも伝えましょう。</p>` },
            { title: "工務店の業者選定・見積依頼をAIで効率化する方法｜2時間→30分に短縮", tag: "GAS活用", image: "images/gyoumu_sum.png", date: "2026.03.04", content: `<p>どの業者に頼むか毎回悩んで、見積依頼メールを書くだけで2時間かかっていませんか？</p>` },
            { title: "【対談】アナログ一筋だった社長がDXに目覚めたきっかけ", tag: "事例", image: "images/jirei_sum.png", date: "2026.03.03", content: `<p>「パソコンは苦手」と言っていたベテラン社長が、孫と遊ぶ時間を確保するためにスマホアプリを導入し、利益率を改善させた実話です。</p>` },
            { title: "「施主様向けLINE」で満足度を高める進捗報告のコツ", tag: "アフター", image: "images/after_sum.png", date: "2026.03.02", content: `<p>写真に対して「今日は断熱材が入りました。これで冬も暖かく過ごせますよ」といった気の利いた一言をAIに生成させましょう。</p>` },
            { title: "補助金申請の書類作成をChatGPTで半自動化する方法", tag: "AI活用", image: "images/aikatsuyou_sum.png", date: "2026.03.01", content: `<p>補助金の申請書類作成は複雑ですが、過去の採択事例をAIに読み込ませることで、作業時間は劇的に短縮できます。</p>` },
            { title: "工務店のHP問い合わせ対応をAI・GASで24時間自動化する方法｜機会損失をゼロに", tag: "GAS活用", image: "images/gyoumu_sum.png", date: "2026.02.28", content: `<p>夜中に届いた問い合わせ、翌朝まで放置していませんか？</p>` },
            { title: "工務店の請求書の受取・内容確認をAIで自動化する方法｜月4時間→30分に短縮", tag: "GAS活用", image: "images/keiri_sum.png", date: "2026.02.27", content: `<p>業者から届く大量の請求書の転記・照合に毎月4時間以上かかっていませんか？</p>` },
            { title: "工務店の工事進捗をLINE×GASで施主へ自動報告する方法｜毎日5分で信頼を積む", tag: "GAS活用", image: "images/genba_sum.png", date: "2026.02.26", content: `<p>「工事はどうなっていますか？」という施主からの電話、毎日かかってきていませんか？</p>` },
            { title: "工務店の新人・中途社員の研修・教育をAIで効率化する方法｜研修準備半日→2時間に短縮", tag: "GAS活用", image: "images/gyoumu_sum.png", date: "2026.02.25", content: `<p>新人が入るたびに同じことを教えるのに半日以上かかっていませんか？</p>` },
            { title: "工務店の法令・申請業務をAI・GASで効率化する方法【完全まとめ】", tag: "GAS活用", image: "images/gyoumu_sum.png", date: "2026.02.24", content: `<p>法令対応は「なんとかなっている」ではなく、本当に大丈夫ですか？</p>` },
            { title: "工務店の名刺・書類の管理をAIで効率化する方法｜月2時間→30分に短縮", tag: "GAS活用", image: "images/gyoumu_sum.png", date: "2026.02.23", content: `<p>もらった名刺が引き出しに山積みのまま、必要なときに探せない状況になっていませんか？</p>` },
            { title: "BuildMateが考える、10年後の工務店の姿", tag: "AI活用", image: "images/aikatsuyou_sum.png", date: "2026.02.22", content: `<p>AIは敵ではなく、面倒な作業を肩代わりしてくれるパートナーです。人が「人らしい仕事」に集中できる未来を作りましょう。</p>` },
            { title: "工務店の要望・敷地情報の整理をAIで自動化する方法｜1時間→15分に短縮", tag: "GAS活用", image: "images/gyoumu_sum.png", date: "2026.02.21", content: `<p>ヒアリングシートの内容を設計に使える形に整理するのに1時間かかっていませんか？</p>` },
            { title: "工務店の見積書確認・請求書発行をAI・GASで自動化する方法｜請求漏れをゼロに", tag: "GAS活用", image: "images/keiri_sum.png", date: "2026.02.20", content: `<p>「あの現場、請求書を送り忘れていた」は笑えない話です。</p>` },
            { title: "工務店の工程表作成・更新・共有をAI・GASで自動化する方法｜3時間→30分を実現", tag: "GAS活用", image: "images/genba_sum.png", date: "2026.02.19", content: `<p>工程表を作るたびに3時間かかっていませんか？</p>` },
            { title: "工務店の原価計算・見積書の作成をAI・GASで自動化する方法｜3時間→30分に短縮", tag: "GAS活用", image: "images/keiri_sum.png", date: "2026.02.18", content: `<p>見積書を作るたびに原価を調べ直して3時間かかっていませんか？</p>` },
            { title: "工務店のお客様対応をAI・GASで効率化する方法｜引渡し後フォローまで自動化", tag: "GAS活用", image: "images/gyoumu_sum.png", date: "2026.02.17", content: `<p>工務店のお客様対応業務をAI・GASで効率化する方法を解説します。</p>` },
            { title: "工務店の職人・業者の入場管理をGASで自動化する方法｜毎日15分→自動化", tag: "GAS活用", image: "images/genba_sum.png", date: "2026.02.16", content: `<p>誰が現場に入っているか、いつ来ていつ帰ったか、正確に把握できていますか？</p>` },
            { title: "工務店の建設業法に基づく帳簿・書類保管をGASで自動化する方法｜月2時間→自動化", tag: "GAS活用", image: "images/gas_sum.png", date: "2026.02.15", content: `<p>建設業法で保管が義務付けられている書類を適切に管理できていますか？</p>` },
            { title: "工務店の保証書の発行・管理をGASで自動化する方法｜毎回1時間→自動化", tag: "GAS活用", image: "images/gas_sum.png", date: "2026.02.14", content: `<p>保証書の発行を忘れたり、保証期限を把握できていないことはありませんか？</p>` },
            { title: "工務店ホームページのSEO対策、AIならここまでできる", tag: "AI活用", image: "images/aikatsuyou_sum.png", date: "2026.02.13", content: `<p>「地域名 + 注文住宅」で検索上位を狙うため、キーワード選定から記事作成までをAIと二人三脚で行いましょう。</p>` },
            { title: "工務店の外注費の単価管理・契約書整備をAI・GASで自動化する方法｜月2時間→30分に短縮", tag: "GAS活用", image: "images/gas_sum.png", date: "2026.02.11", content: `<p>外注業者との単価交渉の根拠がなく、毎回なんとなく決めていませんか？</p>` },
            { title: "工務店の社内連絡・通達をGASで自動化する方法｜30分→3分に短縮", tag: "GAS活用", image: "images/gas_sum.png", date: "2026.02.10", content: `<p>同じ連絡を複数の方法で手動送信するのに毎回30分かかっていませんか？</p>` },
            { title: "【失敗談】高いシステムを導入しても現場が使ってくれない理由", tag: "事例", image: "images/jirei_sum.png", date: "2026.02.09", content: `<p>多機能すぎるシステムは定着しません。成功の鍵は、現場の職人が普段使い慣れている「LINE」を入り口にすることです。</p>` },
            { title: "工務店の採用・外注をAI・GASで効率化する方法｜求人票から研修・単価管理まで自動化", tag: "GAS活用", image: "images/gyoumu_sum.png", date: "2026.02.08", content: `<p>工務店の採用・外注業務をAI・GASで効率化する方法を解説します。</p>` },
            { title: "工務店の引渡し書類の準備・説明をAI・GASで効率化する方法｜2時間→30分に短縮", tag: "GAS活用", image: "images/gyoumu_sum.png", date: "2026.02.07", content: `<p>引渡し当日に書類の準備が間に合わず、バタバタした経験はありませんか？</p>` },
            { title: "工務店の材料の搬入・納期確認をGASで自動化する方法｜毎日30分→自動化", tag: "GAS活用", image: "images/gas_sum.png", date: "2026.02.06", content: `<p>材料が届かずに現場が止まった、という経験はありませんか？</p>` },
            { title: "経理担当が泣いて喜ぶ！レシート読み取りと仕訳の自動化", tag: "業務効率化", image: "images/gyoumu_sum.png", date: "2026.02.05", content: `<p>レシートをスマホで撮影するだけで、AIが日付・金額・勘定科目を読み取って会計ソフトに連動させます。</p>` },
            { title: "工務店の要望整理・プラン提案をAIで自動化する方法｜2時間→30分に短縮", tag: "GAS活用", image: "images/gyoumu_sum.png", date: "2026.02.04", content: `<p>ヒアリングメモを整理して提案書にまとめるだけで2時間かかっていませんか？</p>` },
            { title: "工務店の確認申請・完了検査の申請管理をGASで自動化する方法｜月2時間→自動化", tag: "GAS活用", image: "images/gas_sum.png", date: "2026.02.02", content: `<p>確認申請の期限を管理しきれず工程が押してしまったことはありませんか？</p>` },
            { title: "工務店のアフター対応をAI・GASで効率化する方法｜点検・クレーム・OB客管理を自動化", tag: "GAS活用", image: "images/genba_sum.png", date: "2026.02.01", content: `<p>工務店のアフター対応業務をAI・GASで効率化する方法を解説します。</p>` },
            { title: "工務店の法令・申請をAI・GASで効率化する方法｜建設業許可から廃棄物管理まで自動化", tag: "GAS活用", image: "images/gyoumu_sum.png", date: "2026.01.31", content: `<p>工務店の法令・申請業務をAI・GASで効率化する方法を解説します。</p>` },
            { title: "工務店の顧客対応放置を防ぐフォローアラートをGASで自動化する方法", tag: "GAS活用", image: "images/gas_sum.png", date: "2026.01.30", content: `<p>「また連絡しようと思っていたら、他社で決まっていた」という経験はありませんか？</p>` },
            { title: "工務店の施工内容・図面の共有をGASで自動化する方法｜毎回15分→自動化", tag: "GAS活用", image: "images/genba_sum.png", date: "2026.01.29", content: `<p>古いバージョンの図面で業者が施工してしまった、という経験はありませんか？</p>` },
            { title: "若手社員が育つ！AIを使ったロールプレイング研修", tag: "採用", image: "images/saiyou_sum.png", date: "2026.01.28", content: `<p>営業の練習相手をAIが務めます。様々な性格のお客様をAIに演じさせ、チャットや音声で商談練習を行いましょう。</p>` },
            { title: "工務店の間取りプラン・外観プランの作成をAIで効率化する方法｜半日→1時間に短縮", tag: "GAS活用", image: "images/gyoumu_sum.png", date: "2026.01.27", content: `<p>お客様への最初のプレゼン用プランを作るのに毎回半日かかっていませんか？</p>` },
            { title: "工務店の安全管理（KY活動・ヒヤリハット）をAI・GASで自動化する方法｜30分→10分に短縮", tag: "GAS活用", image: "images/genba_sum.png", date: "2026.01.26", content: `<p>KY活動が形骸化して、毎回同じような記録になっていませんか？</p>` },
            { title: "月8万円の削減！工務店がAI導入で最初にやるべき3つのこと", tag: "AI活用", image: "images/aikatsuyou_sum.png", date: "2026.01.25", content: `<p class="font-bold text-xl mb-6 text-wa-brand">なぜ、あの工務店は残業ゼロなのか？</p><p>多くの工務店様から「AIって難しそう」という声をいただきます。しかし、実は<strong>無料のChatGPTやGoogleのツールを使うだけで、事務作業の時間は半分以下にできる</strong>のです。</p><h4 class="font-bold text-xl mt-8 mb-4 text-wa-brand border-b-2 border-wa-brand/20 pb-2">1. ブログ執筆の自動化</h4><p>「ネタがない」と悩む必要はありません。AIに「30代の子育て世代に向けた、自然素材の家のメリットを3つ挙げて」と頼むだけで、プロ並みの記事構成が5秒で完成します。</p><ul class="list-disc pl-5 mb-6 space-y-2 text-wa-text/80 bg-wa-bg p-4 rounded-lg"><li>キーワード選定から構成案までAIが担当</li><li>誤字脱字のチェックも一瞬</li></ul>` },
            { title: "工務店の業者への工程変更・発注内容をLINE×GASで自動通知する方法", tag: "GAS活用", image: "images/genba_sum.png", date: "2026.01.24", content: `<p>「聞いていない」「連絡が来ていない」——業者とのすれ違いが現場を止めていませんか？</p>` },
            { title: "工務店の工事進捗報告をAI・GASで自動化する方法｜30分/件→5分を実現", tag: "GAS活用", image: "images/genba_sum.png", date: "2026.01.23", content: `<p>工事中のお客様への連絡、ついつい後回しになっていませんか？</p>` },
            { title: "工務店の社内会議の議事録作成をAIで自動化する方法｜45分→5分に短縮", tag: "GAS活用", image: "images/gyoumu_sum.png", date: "2026.01.22", content: `<p>会議が終わった後の議事録作成に、また30〜45分かかっていませんか？</p>` },
            { title: "リフォーム営業の成約率を上げる「即レス」の仕組みづくり", tag: "営業", image: "images/eigyou_sum.png", date: "2026.01.21", content: `<p>顧客は「返信が早い業者」を選びます。問い合わせメールの内容をAIが解析し、最適な返信文案を自動生成してスマホに通知するシステムで、一次対応のスピードを上げましょう。</p>` },
            { title: "工務店の売上・利益の月次集計をGASで自動化する方法｜月4時間→自動化", tag: "GAS活用", image: "images/keiri_sum.png", date: "2026.01.20", content: `<p>月次の売上・利益が把握できるのがいつも翌月半ば以降になっていませんか？</p>` },
            { title: "工務店の業者対応をAI・GASで効率化する方法｜発注書・工程調整・請求確認を自動化", tag: "GAS活用", image: "images/gyoumu_sum.png", date: "2026.01.19", content: `<p>工務店の業者対応業務をAI・GASで効率化する方法を解説します。</p>` },
            { title: "工務店の求人票の作成・媒体掲載をAIで効率化する方法｜3時間→30分に短縮", tag: "GAS活用", image: "images/gyoumu_sum.png", date: "2026.01.18", content: `<p>求人票を書くのが苦手で、採用媒体の掲載が後回しになっていませんか？</p>` },
            { title: "工務店の仕様書・仕上げ表の作成をAI・GASで自動化する方法｜2時間→30分に短縮", tag: "GAS活用", image: "images/genba_sum.png", date: "2026.01.17", content: `<p>仕様書を毎回ゼロから作っていて、記載漏れが後からトラブルになったことはありませんか？</p>` },
            { title: "工務店の入金確認・管理台帳をGASで自動更新する方法｜未入金アラートで入金遅延を防ぐ", tag: "GAS活用", image: "images/keiri_sum.png", date: "2026.01.16", content: `<p>月末の入金照合、何時間かかっていますか？</p>` },
            { title: "VR内覧会で遠方のお客様ともスムーズに商談する", tag: "営業", image: "images/eigyou_sum.png", date: "2026.01.15", content: `<p>360度カメラとVRツールを使えば、遠方のお客様にも、まるでその場にいるような案内が可能です。</p>` },
            { title: "工務店の施工写真整理・報告書作成をAI・GASで自動化する方法｜1時間→10分を実現", tag: "GAS活用", image: "images/genba_sum.png", date: "2026.01.14", content: `<p>現場から帰って、また写真の仕分けですか？</p>` },
            { title: "工務店の図面の修正・バージョン管理をGASで自動化する方法｜毎回30分→自動化", tag: "GAS活用", image: "images/genba_sum.png", date: "2026.01.13", content: `<p>図面を修正するたびに関係者全員への通知と古いバージョンの整理に追われていませんか？</p>` },
            { title: "Z世代の職人を採用するためのSNS活用メソッド", tag: "採用", image: "images/saiyou_sum.png", date: "2026.01.12", content: `<p>求人媒体にお金をかけるよりも、TikTokやInstagramのリール動画が採用に直結する時代です。AIを使って「バズる」台本を作り、スマホ1台で撮影しましょう。</p>` },
            { title: "工務店の完成見学会の企画・告知をAI・GASで自動化する方法｜4時間→1時間に短縮", tag: "GAS活用", image: "images/gyoumu_sum.png", date: "2026.01.11", content: `<p>見学会の告知準備に追われて、肝心の当日対応が疎かになっていませんか？</p>` },
            { title: "工務店の工程調整・入場日時のすり合わせをGASで自動化する方法｜1時間→15分に短縮", tag: "GAS活用", image: "images/genba_sum.png", date: "2026.01.10", content: `<p>複数の業者の入場スケジュールを調整するのに、毎回1時間以上かかっていませんか？</p>` },
            { title: "工務店の経費精算・領収書の整理をAIで自動化する方法｜月5時間→1時間に短縮", tag: "GAS活用", image: "images/keiri_sum.png", date: "2026.01.08", content: `<p>月末に領収書の山を前にして精算作業に半日かかっていませんか？</p>` },
            { title: "工務店の発注書の作成・送付・確認をAI・GASで自動化する方法｜30分→5分に短縮", tag: "GAS活用", image: "images/gas_sum.png", date: "2026.01.07", content: `<p>発注書を毎回Excelで作って印刷してFAXして、という作業がまだ続いていませんか？</p>` },
            { title: "工務店の補助金・助成金の申請書類をAIで効率化する方法｜丸1日→半日に短縮", tag: "GAS活用", image: "images/keiri_sum.png", date: "2026.01.06", content: `<p>補助金の申請書を書くのに丸1日かかって、締切ギリギリになっていませんか？</p>` },
            { title: "工務店の営業・集客をAI・GASで効率化する方法｜問い合わせ対応から追客まで自動化", tag: "GAS活用", image: "images/gyoumu_sum.png", date: "2026.01.05", content: `<p>工務店の営業・集客業務をAI・GASで効率化する方法を解説します。</p>` },
            { title: "工務店の点検報告書の作成・送付をAI・GASで自動化する方法｜1時間→10分に短縮", tag: "GAS活用", image: "images/genba_sum.png", date: "2026.01.04", content: `<p>点検のたびに報告書を作って送付するのに1時間かかっていませんか？</p>` },
            { title: "工務店の数量拾い出し（積算）をAIで自動化する方法｜丸1日→2時間に短縮", tag: "GAS活用", image: "images/keiri_sum.png", date: "2026.01.03", content: `<p>積算作業に丸1日かかって見積書の提出が遅れていませんか？</p>` },
            { title: "工務店の税理士への資料提出をAI・GASで効率化する方法｜月3時間→1時間に短縮", tag: "GAS活用", image: "images/keiri_sum.png", date: "2026.01.02", content: `<p>毎月の税理士への資料まとめ作業に3時間以上かかっていませんか？</p>` },
            { title: "工務店の追客・フォローアップ管理をAI・GASで自動化する方法｜週2時間→30分を実現", tag: "GAS活用", image: "images/gas_sum.png", date: "2026.01.01", content: `<p>見込み客への追客、後回しになっていませんか？</p>` },
            { title: "工務店の紹介客へのお礼・関係維持をAI・GASで自動化する方法｜月2時間→自動化", tag: "GAS活用", image: "images/gas_sum.png", date: "2025.12.31", content: `<p>紹介していただいたお客様へのお礼が、気づけば遅くなってしまっていませんか？</p>` },
            { title: "工務店の日報・週報作成をAIで自動化する方法｜60分→10分に短縮", tag: "GAS活用", image: "images/gyoumu_sum.png", date: "2025.12.30", content: `<p>現場から帰ってきて、疲れた体で日報を書くのに1時間かかっていませんか？</p>` },
            { title: "住宅業界ニュースをGASで自動収集してChatworkに毎朝配信する方法", tag: "GAS活用", image: "images/gas_sum.png", date: "2025.12.28", content: `<p>毎朝の業界ニュースチェック、どのくらい時間をかけていますか？</p>` },
            { title: "工務店のリフォーム再受注活動をAI・GASで自動化する方法｜月4時間→自動化", tag: "GAS活用", image: "images/gas_sum.png", date: "2025.12.27", content: `<p>OB客へのリフォーム提案のタイミングを見極められていますか？</p>` },
            { title: "工務店のHP・SNS更新をAIで自動化する方法｜3時間の作業を30分に短縮", tag: "GAS活用", image: "images/gyoumu_sum.png", date: "2025.12.26", content: `<p>SNSやHPの更新が後回しになり、気づけば何ヶ月も放置していませんか？</p>` },
            { title: "工務店の建設業許可の更新・変更届をAIで効率化する方法｜丸1日→半日に短縮", tag: "GAS活用", image: "images/gyoumu_sum.png", date: "2025.12.25", content: `<p>建設業許可の更新期限が迫ってから慌てて準備していませんか？</p>` },
            { title: "電子契約の導入で印紙代と郵送コストをゼロにする", tag: "業務効率化", image: "images/gyoumu_sum.png", date: "2025.12.24", content: `<p>法改正により建設業界でも電子契約が一般的になりました。収入印紙代、製本の手間、郵送代を削減しましょう。</p>` },
            { title: "工務店の財務・会計をAI・GASで効率化する方法｜請求発行・入金管理・経費精算を自動化", tag: "GAS活用", image: "images/keiri_sum.png", date: "2025.12.23", content: `<p>工務店の財務・会計業務をAI・GASで効率化する方法を解説します。</p>` },
            { title: "工務店の契約書の準備・説明・締結をAIで効率化する方法｜2時間→30分に短縮", tag: "GAS活用", image: "images/gyoumu_sum.png", date: "2025.12.22", content: `<p>契約書の準備に追われて、お客様への説明が十分できていないことはありませんか？</p>` },
            { title: "建設業の資格・免許更新期限をLINE×GASで自動アラートする方法｜法的リスクをゼロに", tag: "GAS活用", image: "images/gas_sum.png", date: "2025.12.21", content: `<p>現場で働く職人の資格、更新期限を把握できていますか？</p>` },
            { title: "現場監督の「言ったつもり」をなくすタスク管理術", tag: "業務効率化", image: "images/gyoumu_sum.png", date: "2025.12.20", content: `<p>口頭指示をスマホに吹き込むだけで、AIがテキスト化し、関係者全員のタスクリストに自動登録します。</p>` },
            { title: "キャッチコピーひとつで反響が変わる！AIコピーライティング術", tag: "営業", image: "images/eigyou_sum.png", date: "2025.12.19", content: `<p>チラシやWebサイトの「見出し」は命です。ターゲットを入力するだけで、AIが刺さるキャッチコピー案を50個出してくれます。</p>` },
            { title: "工務店の融資関連書類対応をAIで効率化する方法｜半日→2時間に短縮", tag: "GAS活用", image: "images/keiri_sum.png", date: "2025.12.18", content: `<p>融資のたびに事業計画書を一から作り直して半日費やしていませんか？</p>` },
            { title: "現場の「ヒヤリハット」情報を共有し安全意識を高める仕組み", tag: "DX", image: "images/dx_sum.png", date: "2025.12.17", content: `<p>ヒヤリハットをスマホ写真で報告し、AIが集計・分析。安全大会の資料まで自動生成することで、安全管理の質が変わります。</p>` },
            { title: "工務店向け補助金・助成金の新着情報をGASで自動監視してLINE・Chatworkに通知する方法", tag: "GAS活用", image: "images/keiri_sum.png", date: "2025.12.15", content: `<p>使えるはずの補助金を、知らずに申請期限が過ぎていたことはありませんか？</p>` },
            { title: "工務店の個人情報保護・情報管理体制をAIで整備する方法｜半日→1時間に短縮", tag: "GAS活用", image: "images/gyoumu_sum.png", date: "2025.12.14", content: `<p>プライバシーポリシーをとりあえず作ったまま、内容を見直していませんか？</p>` },
            { title: "工務店の現場天気予報をGASで自動取得してLINEに通知する方法", tag: "GAS活用", image: "images/genba_sum.png", date: "2025.12.13", content: `<p>現場の天気確認、毎朝スマホでアプリを何個も開いていませんか？</p>` },
            { title: "工務店の業者ごとの評価・実績管理をAI・GASで自動化する方法｜月2時間→自動化", tag: "GAS活用", image: "images/gas_sum.png", date: "2025.12.11", content: `<p>どの業者が品質・納期・対応力に優れているか、感覚でしか把握できていませんか？</p>` },
            { title: "見積書作成のミスをAIチェックで防ぐ方法", tag: "AI活用", image: "images/aikatsuyou_sum.png", date: "2025.12.10", content: `<p>過去の類似工事のデータと照らし合わせ、単価や数量に異常値がないかをAIが自動検知します。</p>` },
            { title: "Googleマップ活用で現場へのルート作成を完全自動化", tag: "DX", image: "images/dx_sum.png", date: "2025.12.08", content: `<p>複数の現場を巡回する際、住所リストを読み込ませるだけで、AIが最適なルートを算出してくれるツールの活用法をご紹介します。</p>` },
            { title: "職人の移動時間を30%削減する「出面管理アプリ」の作り方", tag: "業務効率化", image: "images/gyoumu_sum.png", date: "2025.12.07", content: `<p>現場ごとの職人の配置や稼働時間の管理、まだホワイトボードですか？スマホアプリを導入することで、職人は直行直帰が可能になります。</p><p>ノーコードツールを使えば、低コストかつ短期間で自社専用のアプリを作ることが可能です。</p>` },
            { title: "工務店の構造計算・省エネ計算の依頼管理をGASで自動化する方法｜月2時間→自動化", tag: "GAS活用", image: "images/genba_sum.png", date: "2025.12.06", content: `<p>構造計算の納期を確認し忘れて確認申請が遅れたことはありませんか？</p>` },
            { title: "【事例】商談時間が半分に。即時パース作成で成約率アップ", tag: "事例", image: "images/jirei_sum.png", date: "2025.12.05", content: `<p>「イメージが湧かない」という理由でお客様が迷っている時間、もったいないですよね。画像生成AIを活用すれば、商談中にその場でパース画像を作成可能です。</p><ul class="list-disc pl-5 mb-6 space-y-2 text-wa-text/80 bg-wa-bg p-4 rounded-lg"><li>「もう少し明るい色で」に即座に対応</li><li>家具を配置したイメージも一瞬で生成</li></ul>` },
            { title: "工務店の現場モーニングレポートをGASで自動生成してLINEに配信する方法", tag: "GAS活用", image: "images/genba_sum.png", date: "2025.12.04", content: `<p>毎朝の「今日の天気は？」「今日の入場業者は？」の確認作業、何分かかっていますか？</p>` },
            { title: "建設業の出面管理をLINE×GASで自動化する方法｜打刻から集計まで完全自動", tag: "GAS活用", image: "images/gas_sum.png", date: "2025.12.02", content: `<p>職人の出勤確認、まだ電話で一人ひとり連絡していますか？</p>` },
            { title: "クレームを資産に変える！アフターメンテナンスの自動化戦略", tag: "アフター", image: "images/after_sum.png", date: "2025.12.01", content: `<p>攻めのアフターメンテナンスこそが、次の紹介受注を生みます。過去の修繕データをAIに学習させることで、故障予測が可能になります。</p>` },
        ];

const articleFiles = [
            "079-syunko-gas.html",
            "068-shift-gas.html",
            "114-saiyo-gaichuu-matome.html",
            "110-manifest-gas.html",
            "066-anketo2-gas.html",
            "059-anketo-gas.html",
            "023-newsletter-30min.html",
            "069-kintai-gas.html",
            "099-tenken-gas.html",
            "077-hinshitsu-ai.html",
            "117-gas-guide.html",
            "104-boshu-gas.html",
            "002-afterservice-letter.html",
            "120-task-reminder-gas.html",
            "046-cleaning-scoring.html",
            "113-after-matome.html",
            "022-sekkei-sekisan-ai.html",
            "071-manual-ai.html",
            "044-genba-kanri-ai.html",
            "125-weekly-summary-gas.html",
            "027-ob-dm-gas.html",
            "045-ob-visit-calendar.html",
            "048-meeting-ai.html",
            "123-sns-gemini-gas.html",
            "010-construction-dx-2026.html",
            "014-line-shashin-gas.html",
            "116-koumutenai-guide.html",
            "020-haraisaki-gas.html",
            "072-bihin-gas.html",
            "064-loan-ai.html",
            "060-kyogyo-ai.html",
            "013-voice-daily-report.html",
            "057-chirashi-ai.html",
            "043-inventory-management.html",
            "112-sekkei-sekisan-matome.html",
            "025-claim-gas.html",
            "055-shakunai-kanri-ai.html",
            "098-kakunin-gas.html",
            "052-fax-to-digital.html",
            "080-gyosha-sentei-ai.html",
            "039-analog-ceo-dx.html",
            "028-line-progress-report.html",
            "015-subsidy-chatgpt.html",
            "036-toiawase-gas.html",
            "084-seikyu-uketo-ai.html",
            "011-line-shinchoku-gas.html",
            "105-kensyu-ai.html",
            "115-hourei-matome.html",
            "074-meishi-ai.html",
            "054-buildmate-future.html",
            "091-yobou-ai.html",
            "042-seikyu-gas.html",
            "047-koteihyo-gas.html",
            "095-genka-gas.html",
            "051-customer-taiou-ai.html",
            "075-nyujo-gas.html",
            "109-chobo-gas.html",
            "100-hosho-gas.html",
            "035-seo-for-koumuten.html",
            "106-gaichuu-gas.html",
            "073-renraku-gas.html",
            "019-system-failure-case.html",
            "009-saiyo-gaichuu-ai.html",
            "065-hikiwatashi-gas.html",
            "076-zairyo-gas.html",
            "037-receipt-automation.html",
            "062-plan-ai.html",
            "108-kakunin-shinsei-gas.html",
            "018-after-hosho-ai.html",
            "005-hourei-shinsei-ai.html",
            "121-followup-gas.html",
            "083-zumen-gas.html",
            "041-roleplay-training.html",
            "092-madori-ai.html",
            "078-safety-gas.html",
            "001-ai-cost-reduction.html",
            "007-line-gyosha-gas.html",
            "031-shinchoku-gas.html",
            "070-gijiroku-ai.html",
            "017-quick-reply-sales.html",
            "087-uriage-gas.html",
            "038-gyosha-taiou-ai.html",
            "103-kyujin-ai.html",
            "093-shiyosho-gas.html",
            "040-nyukin-gas.html",
            "050-vr-showcase.html",
            "049-koji-shashin-gas.html",
            "096-zumen-ver-gas.html",
            "012-sns-recruitment-genz.html",
            "058-kenngakukai-gas.html",
            "082-schedule-gas.html",
            "086-keihi-ai.html",
            "081-chuhmon-gas.html",
            "090-hojokin-ai.html",
            "053-eigyo-shukyaku-ai.html",
            "101-hokoku-gas.html",
            "094-sekisan-ai.html",
            "088-zeirishi-gas.html",
            "033-okukyaku-gas.html",
            "061-syoukai-gas.html",
            "067-nippo-ai.html",
            "122-news-chatwork-gas.html",
            "102-reform-gas.html",
            "056-sns-ai.html",
            "107-kensetsu-kyoka-ai.html",
            "030-electronic-contract.html",
            "029-zaimu-kaikei-ai.html",
            "063-keiyaku-ai.html",
            "003-line-shikaku-gas.html",
            "021-task-management.html",
            "032-ai-copywriting.html",
            "089-yushi-ai.html",
            "034-near-miss-safety.html",
            "118-hojokin-gas.html",
            "111-privacy-ai.html",
            "124-tenki-line-gas.html",
            "085-hyoka-gas.html",
            "024-estimate-ai-check.html",
            "026-google-maps-route.html",
            "006-field-attendance-app.html",
            "097-kozo-gas.html",
            "004-estimate-presentation.html",
            "119-morning-report-gas.html",
            "016-line-deming-gas.html",
            "008-claim-to-asset.html",
        ];
